# The Docker image that will be used to build your app
image: node:22.14.0

before_script:
  # Functions that should be executed before the build script is run
  - npm ci

create-pages:
  variables:
    # Optimize Git in the CI/CD process.
    GIT_STRATEGY: fetch
    GIT_DEPTH: 1
    GIT_SUBMODULE_STRATEGY: none
  stage: build
  script:
    # Specify the steps involved to build your app here
    - git submodule update --init --recursive --depth 1
    - npm run build
  pages: true  # publishes the default public directory

  # Trigger rules
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

